apiVersion: v1
kind: Service
metadata:
  name: ecomarket-frontend-svc
  namespace: ecomarket
  labels:
    app: ecomarket-frontend
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: ecomarket-frontend
  type: NodePort
  #type: LoadBalancer
